import {auth,db,app} from "./firebase.js";
import {firebaseConfig,ADMIN_UID,CUSTOMER_EMAIL_SUFFIX} from "./firebase-config.js";
import {onAuthStateChanged,signOut,createUserWithEmailAndPassword,updatePassword} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {initializeApp,getApps} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import {getAuth as getAuth2,signOut as signOut2} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {collection,getDocs,getDoc,doc,setDoc,addDoc,updateDoc,deleteDoc,query,where,orderBy,limit,serverTimestamp,writeBatch} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const seed=await (await fetch("./data/products.json")).json();
const $=s=>document.querySelector(s),main=$("#main"),modal=$("#modal"),body=$("#modalBody"),money=n=>`₹${Number(n||0).toFixed(2)}`,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let cache={customers:[],medicines:[],orders:[],bills:[],purchases:[],ledger:[],profit:[]};
async function getAll(c){return (await getDocs(collection(db,c))).docs.map(x=>({id:x.id,...x.data()}))}async function refresh(){const names=Object.keys(cache);for(const n of names){try{cache[n]=await getAll(n==='medicines'?'medicinesPublic':n)}catch{cache[n]=[]}}}
function table(head,rows){return `<div class="table-wrap"><table class="table"><thead><tr>${head.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.join("")||`<tr><td colspan="${head.length}">No records.</td></tr>`}</tbody></table></div>`}
function open(html){body.innerHTML=html;modal.classList.remove("hidden")}$("#close").onclick=()=>modal.classList.add("hidden");
function nav(){document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.view)})}
async function render(v){await refresh();
if(v==='dashboard'){const today=new Date().toISOString().slice(0,10),tp=cache.profit.filter(x=>x.date===today).reduce((a,x)=>a+Number(x.profit||0),0);main.innerHTML=`<h1>Dashboard</h1><div class="cards"><div class="stat">Customers<div class="big">${cache.customers.length}</div></div><div class="stat">Medicines<div class="big">${cache.medicines.length}</div></div><div class="stat">Orders<div class="big">${cache.orders.length}</div></div><div class="stat">Today's Profit<div class="big">${money(tp)}</div></div></div><div class="panel"><h2>Catalog setup</h2><p>Source catalog is loaded from the EUPHONY price-list file. PDF Rate is treated as P. Rate; N. Rate stays editable by Admin.</p><button id="seed" class="primary">Import / Update EUPHONY Catalog</button></div>`;$("#seed").onclick=seedCatalog}
if(v==='customers'){main.innerHTML=`<h1>Customers</h1><div class="toolbar"><button id="add" class="primary">+ Add Customer</button><input id="cq" class="input" placeholder="Search name / ID / store"></div>${table(['Customer ID','Name','Store','Mobile','Status','Actions'],cache.customers.map(c=>`<tr><td>${esc(c.customerId)}</td><td>${esc(c.name)}</td><td>${esc(c.storeName)}</td><td>${esc(c.mobile)}</td><td><span class="pill ${c.status==='blacklisted'?'bad':'ok'}">${esc(c.status||'active')}</span></td><td><button class="secondary editc" data-id="${c.id}">Edit</button> <button class="danger-btn blockc" data-id="${c.id}">${c.status==='blacklisted'?'Unblacklist':'Blacklist'}</button></td></tr>`))}`;$("#add").onclick=customerForm;document.querySelectorAll('.editc').forEach(b=>b.onclick=()=>customerForm(cache.customers.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.blockc').forEach(b=>b.onclick=async()=>{const c=cache.customers.find(x=>x.id===b.dataset.id);await updateDoc(doc(db,'customers',c.id),{status:c.status==='blacklisted'?'active':'blacklisted'});render('customers')});}
if(v==='medicines'){main.innerHTML=`<h1>Medicines</h1><div class="toolbar"><button id="add" class="primary">+ Add Medicine</button><button id="import" class="secondary">Import PDF Catalog</button></div>${table(['Name','Salt','Pack','MRP','N. Rate','Stock','Batch','Actions'],cache.medicines.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.salt)}</td><td>${esc(m.pack)}</td><td>${m.mrp==null?'—':money(m.mrp)}</td><td>${m.nRate==null?'Not set':money(m.nRate)}</td><td>${m.stock||0}</td><td>${esc(m.batch)}</td><td><button class="secondary editm" data-id="${m.id}">Edit</button> <button class="danger-btn delm" data-id="${m.id}">Delete</button></td></tr>`))}`;$("#add").onclick=()=>medicineForm();$("#import").onclick=seedCatalog;document.querySelectorAll('.editm').forEach(b=>b.onclick=()=>medicineForm(cache.medicines.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.delm').forEach(b=>b.onclick=async()=>{if(confirm('Delete medicine?')){await deleteDoc(doc(db,'medicinesPublic',b.dataset.id));await deleteDoc(doc(db,'medicinesPrivate',b.dataset.id));render('medicines')}})}
if(v==='purchases'){main.innerHTML=`<h1>Purchases & Stock</h1><div class="toolbar"><button id="add" class="primary">+ Purchase Entry</button></div>${table(['Date','Supplier','Invoice','Medicine','Batch','P. Rate','Qty'],cache.purchases.map(p=>`<tr><td>${esc(p.date)}</td><td>${esc(p.supplier)}</td><td>${esc(p.invoice)}</td><td>${esc(p.medicineName)}</td><td>${esc(p.batch)}</td><td>${money(p.pRate)}</td><td>${p.qty}</td></tr>`))}`;$("#add").onclick=purchaseForm}
if(v==='orders'){main.innerHTML=`<h1>Orders</h1>${table(['Order ID','Customer','Date','Total','Status','Action'],cache.orders.map(o=>`<tr><td>${esc(o.orderId)}</td><td>${esc(o.customerName)}<br>${esc(o.storeName)}</td><td>${esc(o.date)}</td><td>${money(o.total)}</td><td><span class="pill ${o.status==='confirmed'?'ok':''}">${esc(o.status)}</span></td><td>${o.status==='pending'?`<button class="primary confirm" data-id="${o.id}">Confirm & Bill</button>`:'—'}</td></tr>`))}`;document.querySelectorAll('.confirm').forEach(b=>b.onclick=()=>confirmOrder(cache.orders.find(x=>x.id===b.dataset.id)))}
if(v==='bills'){main.innerHTML=`<h1>Bills</h1>${table(['Bill No.','Order','Customer','Date','Total','Action'],cache.bills.map(b=>`<tr><td>${esc(b.billNo)}</td><td>${esc(b.orderId)}</td><td>${esc(b.customerName)}</td><td>${esc(b.date)}</td><td>${money(b.total)}</td><td><button class="secondary print" data-id="${b.id}">Print</button></td></tr>`))}`;document.querySelectorAll('.print').forEach(b=>b.onclick=()=>printBill(cache.bills.find(x=>x.id===b.dataset.id)))}
if(v==='ledger'){const bal=cache.ledger.reduce((a,x)=>a+(x.type==='sale'?Number(x.amount||0):-Number(x.amount||0)),0);main.innerHTML=`<h1>Ledger / Outstanding</h1><div class="stat">Overall Outstanding<div class="big">${money(bal)}</div></div><div class="toolbar"><button id="pay" class="primary">+ Record Payment</button></div>${table(['Date','Customer','Type','Amount','Reference','Note'],cache.ledger.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.customerName)}</td><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${esc(x.reference)}</td><td>${esc(x.note)}</td></tr>`))}`;$("#pay").onclick=paymentForm}
if(v==='reports'){const sales=cache.bills.reduce((a,x)=>a+Number(x.total||0),0),profit=cache.profit.reduce((a,x)=>a+Number(x.profit||0),0),qty=cache.orders.reduce((a,o)=>a+(o.items||[]).reduce((b,i)=>b+Number(i.qty||0),0),0);main.innerHTML=`<h1>Reports</h1><div class="cards"><div class="stat">Total Sales<div class="big">${money(sales)}</div></div><div class="stat">Total Profit<div class="big">${money(profit)}</div></div><div class="stat">Units Sold<div class="big">${qty}</div></div></div><div class="panel"><h2>Customer Sales</h2>${table(['Customer','Bills','Sales'],cache.customers.map(c=>{const bs=cache.bills.filter(b=>b.customerUid===c.id),s=bs.reduce((a,x)=>a+Number(x.total||0),0);return `<tr><td>${esc(c.name||c.customerId)}</td><td>${bs.length}</td><td>${money(s)}</td></tr>`}))}</div>`}
if(v==='profit'){const today=new Date().toISOString().slice(0,10),t=cache.profit.filter(x=>x.date===today).reduce((a,x)=>a+Number(x.profit||0),0);main.innerHTML=`<h1>Profit Wallet</h1><div class="cards"><div class="stat">Today's Profit<div class="big">${money(t)}</div></div><div class="stat">All Time<div class="big">${money(cache.profit.reduce((a,x)=>a+Number(x.profit||0),0))}</div></div></div>${table(['Date','Order','Medicine','N. Rate','GST','Transport','P. Rate','Profit'],cache.profit.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.orderId)}</td><td>${esc(x.medicineName)}</td><td>${money(x.nRate)}</td><td>${money(x.gst)}</td><td>${money(x.transport)}</td><td>${money(x.pRate)}</td><td>${money(x.profit)}</td></tr>`))}`}
if(v==='settings'){const s=await getDoc(doc(db,'settings','main'));const d=s.exists()?s.data():{};main.innerHTML=`<h1>Settings</h1><div class="panel"><form id="sf" class="form grid2"><label>Company Name<input id="sn" value="${esc(d.name||'Zeno Life Medicare')}"></label><label>Mobile<input id="sm" value="${esc(d.mobile||'')}"></label><label>Address<textarea id="sa">${esc(d.address||'')}</textarea></label><label>Email<input id="se" value="${esc(d.email||'')}"></label><button class="primary">Save Company Settings</button><div id="sx" class="msg"></div></form></div>`;$("#sf").onsubmit=async e=>{e.preventDefault();await setDoc(doc(db,'settings','main'),{name:$("#sn").value,mobile:$("#sm").value,address:$("#sa").value,email:$("#se").value},{merge:true});$("#sx").textContent='Saved.'}}
}
async function customerForm(c){open(`<h2>${c?'Edit':'Add'} Customer</h2><form id="cf" class="form grid2"><label>Customer ID<input id="id" value="${esc(c?.customerId||'')}" ${c?'readonly':''} required></label><label>Password ${c?'(leave blank to keep current)':''}<input id="pw" type="password" ${c?'':'required'}></label><label>Name<input id="name" value="${esc(c?.name||'')}" required></label><label>Store Name<input id="store" value="${esc(c?.storeName||'')}" required></label><label>Mobile<input id="mobile" value="${esc(c?.mobile||'')}"></label><label>Address<textarea id="address">${esc(c?.address||'')}</textarea></label><button class="primary">Save Customer</button><div id="fm" class="msg"></div></form>`);$("#cf").onsubmit=async e=>{e.preventDefault();const m=$("#fm"),id=$("#id").value.trim().toLowerCase(),pw=$("#pw").value;try{if(!c){if(pw.length<6){m.textContent='Password minimum 6 characters.';return}let saApp=getApps().find(a=>a.name==='customerCreator');if(!saApp)saApp=initializeApp(firebaseConfig,'customerCreator');const sa=getAuth2(saApp),u=await createUserWithEmailAndPassword(sa,id+CUSTOMER_EMAIL_SUFFIX,pw);await setDoc(doc(db,'customers',u.user.uid),{customerId:id,name:$("#name").value,storeName:$("#store").value,mobile:$("#mobile").value,address:$("#address").value,status:'active',createdAt:serverTimestamp()});await signOut2(sa)}else{await updateDoc(doc(db,'customers',c.id),{name:$("#name").value,storeName:$("#store").value,mobile:$("#mobile").value,address:$("#address").value,updatedAt:serverTimestamp()})}modal.classList.add('hidden');render('customers')}catch(e){m.textContent=e.message}}}
async function medicineForm(m){open(`<h2>${m?'Edit':'Add'} Medicine</h2><form id="mf" class="form grid2"><label>Name<input id="name" value="${esc(m?.name||'')}" required></label><label>Category<input id="cat" value="${esc(m?.category||'')}" placeholder="Tablet / Syrup / Injection..."></label><label>Salt / Composition<textarea id="salt">${esc(m?.salt||'')}</textarea></label><label>Pack<input id="pack" value="${esc(m?.pack||'')}"></label><label>Style<input id="style" value="${esc(m?.style||'')}"></label><label>MRP<input id="mrp" type="number" step="0.01" value="${m?.mrp??''}"></label><label>N. Rate<input id="nr" type="number" step="0.01" value="${m?.nRate??''}"></label><label>Stock<input id="stock" type="number" value="${m?.stock??0}"></label><label>Batch<input id="batch" value="${esc(m?.batch||'')}"></label><label>Expiry<input id="expiry" value="${esc(m?.expiry||'')}" placeholder="MM/YYYY"></label><label>Image URL<input id="image" value="${esc(m?.image||'')}"></label><label>P. Rate<input id="pr" type="number" step="0.01" value="${m?.pRate??''}"></label><label>GST / unit<input id="gst" type="number" step="0.01" value="${m?.gst??''}"></label><label>Transport / unit<input id="tr" type="number" step="0.01" value="${m?.transport??''}"></label><button class="primary">Save Medicine</button></form>`);$("#mf").onsubmit=async e=>{e.preventDefault();const id=m?.id||crypto.randomUUID(),pub={name:$("#name").value,category:$("#cat").value,salt:$("#salt").value,pack:$("#pack").value,style:$("#style").value,mrp:$("#mrp").value===''?null:Number($("#mrp").value),nRate:$("#nr").value===''?null:Number($("#nr").value),stock:Number($("#stock").value||0),batch:$("#batch").value,expiry:$("#expiry").value,image:$("#image").value,updatedAt:serverTimestamp()};const pri={pRate:$("#pr").value===''?null:Number($("#pr").value),gst:Number($("#gst").value||0),transport:Number($("#tr").value||0),updatedAt:serverTimestamp()};await setDoc(doc(db,'medicinesPublic',id),pub,{merge:true});await setDoc(doc(db,'medicinesPrivate',id),pri,{merge:true});modal.classList.add('hidden');render('medicines')}}
async function seedCatalog(){if(!confirm(`Import ${seed.length} source products? Existing IDs will be updated.`))return;const chunks=[];for(let i=0;i<seed.length;i+=450)chunks.push(seed.slice(i,i+450));for(const chunk of chunks){const b=writeBatch(db);chunk.forEach(r=>{const pub={name:r.name,category:r.section,salt:r.salt,pack:r.pack,style:r.style,mrp:r.mrp,nRate:null,stock:0,batch:'',expiry:'',image:''};const pri={pRate:r.pRate,gst:0,transport:0,sourceRateRaw:r.pRateRaw};b.set(doc(db,'medicinesPublic',r.id),pub,{merge:true});b.set(doc(db,'medicinesPrivate',r.id),pri,{merge:true})});await b.commit()}alert('Catalog imported. N. Rate is blank and must be set by Admin.');render('medicines')}
async function purchaseForm(){open(`<h2>Purchase Entry</h2><form id="pf" class="form grid2"><label>Supplier<input id="supplier" required></label><label>Invoice No.<input id="invoice"></label><label>Medicine<select id="med">${cache.medicines.map(m=>`<option value="${m.id}">${esc(m.name)} — ${esc(m.pack)}</option>`).join('')}</select></label><label>Batch<input id="batch"></label><label>Expiry<input id="expiry"></label><label>P. Rate<input id="pr" type="number" step="0.01"></label><label>Quantity<input id="qty" type="number" min="1" required></label><button class="primary">Save Purchase</button></form>`);$("#pf").onsubmit=async e=>{e.preventDefault();const id=$("#med").value,m=cache.medicines.find(x=>x.id===id),qty=Number($("#qty").value);await addDoc(collection(db,'purchases'),{supplier:$("#supplier").value,invoice:$("#invoice").value,medicineId:id,medicineName:m.name,batch:$("#batch").value,expiry:$("#expiry").value,pRate:Number($("#pr").value||0),qty,date:new Date().toISOString().slice(0,10),createdAt:serverTimestamp()});await updateDoc(doc(db,'medicinesPublic',id),{stock:Number(m.stock||0)+qty,batch:$("#batch").value,expiry:$("#expiry").value});modal.classList.add('hidden');render('purchases')}}
async function confirmOrder(o){if(!confirm(`Confirm ${o.orderId}? Stock will be reduced and bill created.`))return;for(const i of(o.items||[])){const m=cache.medicines.find(x=>x.id===i.medicineId);if(!m||Number(m.stock||0)<Number(i.qty||0)){alert(`Insufficient stock: ${i.name}`);return}}for(const i of(o.items||[])){const m=cache.medicines.find(x=>x.id===i.medicineId);await updateDoc(doc(db,'medicinesPublic',m.id),{stock:Number(m.stock||0)-Number(i.qty||0)})}const billNo='BILL-'+Date.now(),date=new Date().toISOString().slice(0,10);await addDoc(collection(db,'bills'),{billNo,orderId:o.orderId,customerUid:o.customerUid,customerName:o.customerName,storeName:o.storeName,mobile:o.mobile,total:o.total,items:o.items||[],date,createdAt:serverTimestamp()});await updateDoc(doc(db,'orders',o.id),{status:'confirmed',billNo,confirmedAt:serverTimestamp()});await addDoc(collection(db,'ledger'),{customerUid:o.customerUid,customerName:o.customerName,type:'sale',amount:o.total,reference:billNo,note:'Medicine sale',date,createdAt:serverTimestamp()});for(const i of(o.items||[])){const p=await getDoc(doc(db,'medicinesPrivate',i.medicineId));const d=p.exists()?p.data():{},n=Number(i.nRate||0),g=Number(d.gst||0),t=Number(d.transport||0),pr=Number(d.pRate||0);await addDoc(collection(db,'profitTransactions'),{date,orderId:o.orderId,medicineName:i.name,nRate:n,gst:g,transport:t,pRate:pr,profit:n-g-t-pr,qty:Number(i.qty||1),createdAt:serverTimestamp()})}alert('Order confirmed, stock reduced, bill and profit transaction created.');render('orders')}
async function paymentForm(){open(`<h2>Record Customer Payment</h2><form id="payf" class="form"><label>Customer<select id="cus">${cache.customers.map(c=>`<option value="${c.id}">${esc(c.name||c.customerId)}</option>`).join('')}</select></label><label>Amount<input id="amt" type="number" step="0.01" required></label><label>Reference<input id="ref"></label><label>Note<textarea id="note"></textarea></label><button class="primary">Save Payment</button></form>`);$("#payf").onsubmit=async e=>{e.preventDefault();const c=cache.customers.find(x=>x.id===$("#cus").value);await addDoc(collection(db,'ledger'),{customerUid:c.id,customerName:c.name,type:'payment',amount:Number($("#amt").value),reference:$("#ref").value,note:$("#note").value,date:new Date().toISOString().slice(0,10),createdAt:serverTimestamp()});modal.classList.add('hidden');render('ledger')}}
async function printBill(b){const s=await getDoc(doc(db,'settings','main')),d=s.exists()?s.data():{name:'Zeno Life Medicare'};open(`<div class="invoice"><h1>${esc(d.name)}</h1><p>${esc(d.address||'')} ${d.mobile?'• '+esc(d.mobile):''} ${d.email?'• '+esc(d.email):''}</p><hr><div class="grid2"><div>Bill No.: <b>${esc(b.billNo)}</b><br>Date: ${esc(b.date)}</div><div>Customer: <b>${esc(b.customerName)}</b><br>Store: ${esc(b.storeName||'')}<br>Mobile: ${esc(b.mobile||'')}</div></div><br>${table(['S.No.','Medicine','Batch','MRP','N. Rate','Qty','Amount'],(b.items||[]).map((i,n)=>`<tr><td>${n+1}</td><td>${esc(i.name)}</td><td>${esc(i.batch)}</td><td>—</td><td>${money(i.nRate)}</td><td>${i.qty}</td><td>${money(i.nRate*i.qty)}</td></tr>`))}<div class="total"><b>Grand Total</b><b>${money(b.total)}</b></div><p style="margin-top:60px;text-align:right">Authority Signature</p><button class="primary no-print" onclick="window.print()">Print / Save PDF</button></div>`)}
$("#logout").onclick=()=>signOut(auth).then(()=>location.href='index.html');
onAuthStateChanged(auth,async u=>{
  if(!u||u.uid!==ADMIN_UID){location.href='index.html';return}
  nav();
  try {
    await render('dashboard');
  } catch(e) {
    main.innerHTML=`<div class="panel"><h2>Firebase connection problem</h2><p>${esc(e?.message||'Could not load Firestore data.')}</p><p>Authentication successful hai, lekin Firestore data load nahi hua.</p><button class="primary" onclick="location.reload()">Retry</button></div>`;
  }
});
