import {auth,db} from "./firebase.js";
import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {collection,getDocs,getDoc,doc,addDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
let meds=[],cart=[];
const grid=document.querySelector("#medicineGrid"),search=document.querySelector("#search");
const money=n=>"₹"+Number(n||0).toFixed(2);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function draw(q=""){const x=q.toLowerCase();const list=meds.filter(m=>`${m.name} ${m.salt} ${m.pack} ${m.batch}`.toLowerCase().includes(x));document.querySelector("#resultCount").textContent=`${list.length} medicines`;grid.innerHTML=list.map(m=>`<article class="med-card"><img src="${esc(m.image||"https://placehold.co/500x300?text=Medicine")}" onerror="this.src='https://placehold.co/500x300?text=Medicine'"><h3>${esc(m.name)}</h3><div class="muted">${esc(m.salt||"")}</div><div>${esc(m.pack||"")} ${m.batch?`• Batch ${esc(m.batch)}`:""}</div><p>MRP: ${money(m.mrp)}</p><div class="rate">${money(m.nRate)}</div><button class="primary add" data-id="${m.id}" style="margin-top:10px;width:100%">Add to Cart</button></article>`).join("")||"<p>No medicine found.</p>";document.querySelectorAll(".add").forEach(b=>b.onclick=()=>add(meds.find(m=>m.id===b.dataset.id)))}
function add(m){const x=cart.find(i=>i.medicineId===m.id);if(x)x.qty++;else cart.push({medicineId:m.id,name:m.name,batch:m.batch||"",nRate:Number(m.nRate||0),qty:1});drawCart()}
function drawCart(){document.querySelector("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0);document.querySelector("#cartItems").innerHTML=cart.map((x,i)=>`<div class="cart-line"><span>${esc(x.name)}<br><small>${money(x.nRate)} × ${x.qty}</small></span><span>${money(x.nRate*x.qty)}</span><button class="ghost rm" data-i="${i}">−</button></div>`).join("")||"<p>Cart is empty.</p>";document.querySelector("#cartTotal").textContent=money(cart.reduce((a,x)=>a+x.nRate*x.qty,0));document.querySelectorAll(".rm").forEach(b=>b.onclick=()=>{cart[b.dataset.i].qty--;if(cart[b.dataset.i].qty<=0)cart.splice(b.dataset.i,1);drawCart()})}
search.oninput=()=>draw(search.value);document.querySelector("#cartBtn").onclick=()=>document.querySelector("#cartModal").classList.remove("hidden");document.querySelector("#closeCart").onclick=()=>document.querySelector("#cartModal").classList.add("hidden");
document.querySelector("#placeOrder").onclick=async()=>{if(!cart.length)return;const u=auth.currentUser,p=await getDoc(doc(db,"customers",u.uid));if(!p.exists())return;const d=p.data(),total=cart.reduce((a,x)=>a+x.nRate*x.qty,0),orderId="ORD-"+Date.now();await addDoc(collection(db,"orders"),{orderId,customerUid:u.uid,customerName:d.name,storeName:d.storeName,mobile:d.mobile,items:cart,total,status:"pending",date:new Date().toISOString().slice(0,10),createdAt:serverTimestamp()});cart=[];drawCart();document.querySelector("#cartMsg").textContent="Order Sent Successfully. Please wait for confirmation.";setTimeout(()=>document.querySelector("#cartModal").classList.add("hidden"),1800)};
document.querySelector("#logout").onclick=()=>signOut(auth).then(()=>location.href="index.html");
onAuthStateChanged(auth,async u=>{if(!u){location.href="index.html";return}const p=await getDoc(doc(db,"customers",u.uid));if(!p.exists()||p.data().status==="blacklisted"){await signOut(auth);location.href="index.html";return}const d=p.data();document.querySelector("#profileBox").innerHTML=`<h1>Welcome, ${esc(d.name||d.customerId)}</h1><p>${esc(d.storeName||"")} ${d.mobile?`• ${esc(d.mobile)}`:""}</p>`;meds=(await getDocs(collection(db,"medicinesPublic"))).docs.map(x=>({id:x.id,...x.data()}));draw();drawCart()});
