import {auth,db} from "./firebase.js";
import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import {collection,getDocs,getDoc,doc,addDoc,query,where,orderBy,limit,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
let meds=[],cart=[],profile=null;const $=s=>document.querySelector(s),money=n=>`₹${Number(n||0).toFixed(2)}`,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function draw(){const x=$("#q").value.toLowerCase();const a=meds.filter(m=>`${m.name} ${m.salt} ${m.pack} ${m.style} ${m.batch}`.toLowerCase().includes(x));$("#count").textContent=`${a.length} products`;$("#grid").innerHTML=a.map(m=>`<article class="med"><img src="${esc(m.image||"https://placehold.co/500x300?text=Medicine")}" onerror="this.src='https://placehold.co/500x300?text=Medicine'"><h3>${esc(m.name)}</h3><div class="muted">${esc(m.salt)}</div><p>${esc(m.pack)} ${esc(m.style)}</p><p>MRP: ${m.mrp==null?"—":money(m.mrp)}</p><p class="rate">${m.nRate==null?"Rate not set":money(m.nRate)}</p><button class="primary add" data-id="${m.id}" ${m.nRate==null?"disabled":""}>Add to Cart</button></article>`).join("")||`<div class="panel">No medicine found.</div>`;document.querySelectorAll(".add").forEach(b=>b.onclick=()=>{const m=meds.find(x=>x.id===b.dataset.id),i=cart.find(x=>x.medicineId===m.id);i?i.qty++:cart.push({medicineId:m.id,name:m.name,batch:m.batch||"",nRate:Number(m.nRate),qty:1});cartDraw()})}
function cartDraw(){$("#cc").textContent=cart.reduce((a,x)=>a+x.qty,0);$("#modalBody").innerHTML=`<h2>Cart</h2>${cart.map((x,i)=>`<div class="cart-line"><span>${esc(x.name)}<br><small>${money(x.nRate)} × ${x.qty}</small></span><b>${money(x.nRate*x.qty)}</b><button class="secondary rm" data-i="${i}">−</button></div>`).join("")||"<p>Cart is empty.</p>"}<div class="total"><span>Grand Total</span><b>${money(cart.reduce((a,x)=>a+x.nRate*x.qty,0))}</b></div>${cart.length?`<button id="place" class="primary">Place Order</button>`:""}<div id="orderMsg" class="msg"></div>`;document.querySelectorAll(".rm").forEach(b=>b.onclick=()=>{cart[b.dataset.i].qty--;if(cart[b.dataset.i].qty<1)cart.splice(b.dataset.i,1);cartDraw()});$("#place")?.addEventListener("click",place)}
async function place(){const total=cart.reduce((a,x)=>a+x.nRate*x.qty,0),orderId="ORD-"+Date.now();await addDoc(collection(db,"orders"),{orderId,customerUid:auth.currentUser.uid,customerName:profile.name,storeName:profile.storeName,mobile:profile.mobile||"",items:cart,total,status:"pending",date:new Date().toISOString().slice(0,10),createdAt:serverTimestamp()});cart=[];cartDraw();$("#orderMsg").textContent="Order Sent Successfully — Please wait for confirmation.";setTimeout(()=>$("#modal").classList.add("hidden"),1800)}
async function orders(){const s=await getDocs(query(collection(db,"orders"),where("customerUid","==",auth.currentUser.uid),orderBy("createdAt","desc"),limit(50)));$("#modalBody").innerHTML=`<h2>My Orders</h2>${s.docs.map(x=>{const o=x.data();return `<div class="panel"><b>${esc(o.orderId)}</b> • ${esc(o.date)}<br>Total: <b>${money(o.total)}</b><br>Status: <span class="pill ${o.status==='confirmed'?'ok':''}">${esc(o.status)}</span>${o.billNo?`<br>Bill: ${esc(o.billNo)}`:""}</div>`}).join("")||"<p>No orders yet.</p>"}`;$("#modal").classList.remove("hidden")}
$("#q").oninput=draw;$("#cartBtn").onclick=()=>{$("#modal").classList.remove("hidden");cartDraw()};$("#ordersBtn").onclick=orders;$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#logout").onclick=()=>signOut(auth).then(()=>location.href="index.html");
onAuthStateChanged(auth,async u=>{if(!u){location.href="index.html";return}const p=await getDoc(doc(db,"customers",u.uid));if(!p.exists()||p.data().status==="blacklisted"){await signOut(auth);location.href="index.html";return}profile=p.data();$("#profile").innerHTML=`<h1>Welcome, ${esc(profile.name||profile.customerId)}</h1><p>${esc(profile.storeName||"")} ${profile.mobile?`• ${esc(profile.mobile)}`:""}</p>`;const s=await getDocs(collection(db,"medicinesPublic"));meds=s.docs.map(x=>({id:x.id,...x.data()}));draw();const os=await getDocs(query(collection(db,"orders"),where("customerUid","==",u.uid),orderBy("createdAt","desc"),limit(5)));const latest=os.docs.find(x=>x.data().status==="confirmed");if(latest)$("#notice").innerHTML=`<div class="notice">🎉 Your order <b>${esc(latest.data().orderId)}</b> has been confirmed.</div>`});
